version: '3.9'

services:
  clienta1:
    build: .
    image: myquicclient:clienta1
    container_name: clienta1
    cap_add:
      - NET_ADMIN
    networks:
      netA:
        ipv4_address: 172.18.0.10
      netB:
        ipv4_address: 172.19.0.10
    tty: true
    stdin_open: true
    command: zsh
    environment:
      - TZ=America/New_York

  # clienta2:
  #   image: myquicclient:clienta1
  #   container_name: clienta2
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     netA:
  #       ipv4_address: 172.18.0.11
  #     netB:
  #       ipv4_address: 172.19.0.11
  #   tty: true
  #   stdin_open: true
  #   command: zsh
  #   environment:
  #     - TZ=America/New_York

  # clienta3:
  #   image: myquicclient:clienta1
  #   container_name: clienta3
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     netA:
  #       ipv4_address: 172.18.0.12
  #     netB:
  #       ipv4_address: 172.19.0.12
  #   tty: true
  #   stdin_open: true
  #   command: zsh
  #   environment:
  #     - TZ=America/New_York

networks:
  netA:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

  netB:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
